### ISSUE TITLE
SyntaxError inside binaryTree.py

### ISSUE THREAD

**Issue by debbiezhu** [bnmnetp/pythonds#4]
i got a SyntaxError. according to the error message, it indicates that there is something wrong with line 81 inside binaryTree.py
```
 $ python -V                                                                                                  [11:40:23]
Python 2.7.9

 $ python -m pythonds "import pythonds"                                                                       [11:39:02]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python2.7/dist-packages/pythonds/__init__.py", line 1, in <module>
    from .trees import BinaryTree, AVLTree, BinarySearchTree, BinHeap, BinaryTree
  File "/usr/local/lib/python2.7/dist-packages/pythonds/trees/__init__.py", line 7, in <module>
    from .binaryTree import BinaryTree
  File "/usr/local/lib/python2.7/dist-packages/pythonds/trees/binaryTree.py", line 81
    print('(', end=' ')
                  ^
SyntaxError: invalid syntax
FAIL
```

**Comment by bnmnetp** [comment]
The print function is using Python3 syntax

**Comment by babu-shanmugam** [comment]
@bnmnetp Does this mean pythonds does not work in python2.7?

**Comment by bnmnetp** [comment]
Well, this one file made use of an optional parameter to the print function in python3.  Everything else should work fine in either 2.7 or 3.x.   I've also made a fix and released a new version that makes the example above work in 2 or 3.
